import React, { useState } from 'react';
import { X, Download, FileText, Share2, Calendar, TrendingUp, TrendingDown, Check, Sparkles } from 'lucide-react';
import { MonthlyCardExportData, exportMonthlyCardToPNG, exportMonthlyCardToPDF } from '../utils/cardGenerators';
import { formatNaira, formatSignedNaira } from '../engine/calculations';

interface MonthlyCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: MonthlyCardExportData;
  businessName: string;
  onShowToast?: (message: string, type?: 'info' | 'success') => void;
}

export const MonthlyCardModal: React.FC<MonthlyCardModalProps> = ({
  isOpen,
  onClose,
  data,
  businessName,
  onShowToast,
}) => {
  const [isExportingPNG, setIsExportingPNG] = useState(false);
  const [isExportingPDF, setIsExportingPDF] = useState(false);
  const [hasShared, setHasShared] = useState(false);

  if (!isOpen) return null;

  const isProfit = data.netProfit >= 0;

  const handleDownloadPNG = async () => {
    try {
      setIsExportingPNG(true);
      await exportMonthlyCardToPNG(data, businessName);
      onShowToast?.(`Downloaded ${data.monthName} ${data.year} Card as HD Image (PNG).`, 'success');
    } catch (err) {
      console.error('Error exporting PNG:', err);
      onShowToast?.('Failed to generate image. Please try PDF download.', 'info');
    } finally {
      setIsExportingPNG(false);
    }
  };

  const handleDownloadPDF = () => {
    try {
      setIsExportingPDF(true);
      exportMonthlyCardToPDF(data, businessName);
      onShowToast?.(`Downloaded ${data.monthName} ${data.year} Statement (PDF).`, 'success');
    } catch (err) {
      console.error('Error exporting PDF:', err);
      onShowToast?.('Failed to generate PDF.', 'info');
    } finally {
      setIsExportingPDF(false);
    }
  };

  const handleShare = async () => {
    const summaryText = `📊 *${businessName} - ${data.monthName.toUpperCase()} ${data.year} MONTHLY SUMMARY*
💰 Gross Sales: ${formatNaira(data.totalSales)}
📦 Product Costs (COGS): ${formatNaira(data.totalCostOfGoods)}
🧾 Operating Expenses: ${formatNaira(data.totalExpenses)}
✨ Net Operating Result: ${isProfit ? '+' : ''}${formatNaira(data.netProfit)} (${data.netMarginPercent.toFixed(1)}% margin)
📈 Rhythm: ${data.profitableDaysCount} Profitable Days • ${data.lossDaysCount} Loss Days
🏆 Best Day: ${data.bestDay.date ? `${data.bestDay.date} (+${formatNaira(data.bestDay.profit)})` : 'None'}

Generated by Karra - AI Operating System for Informal Merchants.`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `${businessName} - ${data.monthName} ${data.year} Monthly Card`,
          text: summaryText,
        });
        setHasShared(true);
        setTimeout(() => setHasShared(false), 2500);
        return;
      } catch (err: any) {
        if (err?.name === 'AbortError') return;
      }
    }

    try {
      await navigator.clipboard.writeText(summaryText);
      setHasShared(true);
      onShowToast?.('Monthly summary copied to clipboard for WhatsApp.', 'success');
      setTimeout(() => setHasShared(false), 2500);
    } catch {
      const encoded = encodeURIComponent(summaryText);
      window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-slate-950/75 backdrop-blur-xs animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="bg-slate-900 text-white border border-slate-800 w-full sm:max-w-2xl rounded-t-3xl sm:rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh] sm:max-h-[88vh] transition-all"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Mobile Pull Handle */}
        <div className="w-12 h-1.5 bg-slate-700 rounded-full mx-auto my-2.5 sm:hidden shrink-0" />

        {/* Modal Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 flex items-center justify-between bg-slate-900/90">
          <div className="flex items-center space-x-2.5">
            <div className="w-9 h-9 rounded-xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center justify-center font-bold shrink-0">
              <Calendar className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white tracking-tight">
                {data.monthName} {data.year} Monthly Card
              </h3>
              <p className="text-xs text-slate-400">
                Official store performance & operating result summary
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Card Preview */}
        <div className="p-4 sm:p-6 overflow-y-auto space-y-4">
          {/* Visual Digital Card Preview Container */}
          <div className="rounded-2xl border border-slate-700/80 bg-linear-to-b from-slate-800/90 via-slate-900 to-[#0c1322] p-4 sm:p-6 shadow-xl relative overflow-hidden">
            {/* Ambient Corner Glow */}
            <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
            <div className="absolute bottom-0 left-0 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

            {/* Top Bar */}
            <div className="flex items-center justify-between pb-3 border-b border-slate-800 relative z-10">
              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                <Sparkles className="w-3 h-3 mr-1 text-emerald-400" />
                Karra Verified Statement
              </span>
              <span className="text-[11px] font-mono text-slate-400">
                {data.monthName.toUpperCase()} {data.year}
              </span>
            </div>

            {/* Store Name */}
            <div className="pt-3 pb-4 relative z-10">
              <h4 className="text-xl sm:text-2xl font-black text-white tracking-tight">
                {businessName}
              </h4>
              <p className="text-xs text-slate-400">
                Monthly Operating & Cash Flow Record
              </p>
            </div>

            {/* Hero Net Result */}
            <div
              className={`p-4 rounded-xl border relative z-10 mb-4 ${
                isProfit
                  ? 'bg-emerald-950/40 border-emerald-500/30'
                  : 'bg-rose-950/40 border-rose-500/30'
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-300">
                  Net Operating Result (Take-Home Profit)
                </span>
                <span
                  className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                    isProfit ? 'bg-emerald-500 text-white' : 'bg-rose-600 text-white'
                  }`}
                >
                  {isProfit ? 'PROFIT' : 'LOSS'} ({data.netMarginPercent.toFixed(1)}%)
                </span>
              </div>
              <div
                className={`text-2xl sm:text-3xl font-black font-mono mt-1 ${
                  isProfit ? 'text-emerald-400' : 'text-rose-400'
                }`}
              >
                {formatSignedNaira(data.netProfit)}
              </div>
              <div className="text-[11px] text-slate-400 mt-1 flex items-center space-x-2">
                <span>{data.profitableDaysCount} profitable days</span>
                <span>•</span>
                <span>{data.lossDaysCount} loss days</span>
              </div>
            </div>

            {/* 4 Financial KPIs Grid */}
            <div className="grid grid-cols-2 gap-2.5 relative z-10 mb-3 text-xs">
              <div className="p-3 rounded-xl bg-slate-800/60 border border-slate-700/60">
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Gross Sales</span>
                <span className="text-base font-bold text-white font-mono mt-0.5 block truncate">
                  {formatNaira(data.totalSales)}
                </span>
                <span className="text-[10px] text-slate-500 block truncate">{data.totalTransactions} transactions</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-800/60 border border-slate-700/60">
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Product Costs</span>
                <span className="text-base font-bold text-white font-mono mt-0.5 block truncate">
                  {formatNaira(data.totalCostOfGoods)}
                </span>
                <span className="text-[10px] text-slate-500 block truncate">{data.totalItemsSold} items moved</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-800/60 border border-slate-700/60">
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Expenses</span>
                <span className="text-base font-bold text-white font-mono mt-0.5 block truncate">
                  {formatNaira(data.totalExpenses)}
                </span>
                <span className="text-[10px] text-slate-500 block truncate">Rent, transport, utilities</span>
              </div>

              <div className="p-3 rounded-xl bg-slate-800/60 border border-slate-700/60">
                <span className="text-[10px] uppercase font-bold text-slate-400 block">Cash Received</span>
                <span className="text-base font-bold text-emerald-400 font-mono mt-0.5 block truncate">
                  {formatNaira(data.cashReceived)}
                </span>
                <span className="text-[10px] text-slate-500 block truncate">Credit: {formatNaira(data.creditGiven)}</span>
              </div>
            </div>

            {/* Operational Rhythm Bar */}
            <div className="p-3 rounded-xl bg-slate-800/40 border border-slate-700/40 relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-1 text-[11px] text-slate-300">
              <div>
                <span className="text-slate-400">Best Trading Day: </span>
                <strong className="text-white">
                  {data.bestDay.date ? `${data.bestDay.date} (+${formatNaira(data.bestDay.profit, true)})` : 'None logged'}
                </strong>
              </div>
              <div className="text-slate-500 text-[10px]">
                Deterministic cost calculation via Karra
              </div>
            </div>
          </div>
        </div>

        {/* Modal Action Buttons Footer */}
        <div className="p-4 sm:p-5 border-t border-slate-800 bg-slate-900/90 flex flex-wrap items-center gap-2.5">
          <button
            type="button"
            onClick={handleDownloadPNG}
            disabled={isExportingPNG}
            className="flex-1 sm:flex-initial px-4 py-2.5 rounded-xl text-xs font-bold bg-emerald-600 hover:bg-emerald-500 text-white shadow-xs flex items-center justify-center space-x-2 transition-all active:scale-95 cursor-pointer disabled:opacity-50 min-h-[42px]"
            title="Download high-resolution image card (PNG)"
          >
            <Download className="w-4 h-4" />
            <span>{isExportingPNG ? 'Generating...' : 'Download Image (PNG)'}</span>
          </button>

          <button
            type="button"
            onClick={handleDownloadPDF}
            disabled={isExportingPDF}
            className="flex-1 sm:flex-initial px-4 py-2.5 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-white border border-slate-700 shadow-xs flex items-center justify-center space-x-2 transition-all active:scale-95 cursor-pointer disabled:opacity-50 min-h-[42px]"
            title="Download printable monthly statement (PDF)"
          >
            <FileText className="w-4 h-4 text-emerald-400" />
            <span>{isExportingPDF ? 'Generating...' : 'Download PDF Card'}</span>
          </button>

          <button
            type="button"
            onClick={handleShare}
            className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-semibold bg-slate-800/80 hover:bg-slate-800 text-slate-300 hover:text-white border border-slate-700 flex items-center justify-center space-x-1.5 transition-colors cursor-pointer min-h-[42px]"
            title="Share summary to WhatsApp or messaging app"
          >
            {hasShared ? <Check className="w-4 h-4 text-emerald-400" /> : <Share2 className="w-4 h-4" />}
            <span>{hasShared ? 'Shared / Copied!' : 'Share to WhatsApp'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
